---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: enforce-gpu-resource-quota
  annotations:
    policies.kyverno.io/title: Enforce GPU Resource Quota
    policies.kyverno.io/category: GPU Management
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: ResourceQuota
    kyverno.io/kyverno-version: 1.11.0
    policies.kyverno.io/description: >-
      Enforce ResourceQuota resources that limit the total number of GPUs requested within a namespace used for Ray workloads.
spec:
  validationFailureAction: Audit
  rules:
    - name: check-gpu-resource-quota
      match:
        any:
          - resources:
              kinds:
                - ResourceQuota
      validate:
        message: "ResourceQuota must limit the total number of GPUs requested within a namespace."
        pattern:
          spec:
            hard:
              nvidia.com/gpu: "<=10"
