---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: validate-gpu-limits-requests
  annotations:
    policies.kyverno.io/title: Validate GPU Limits and Requests
    policies.kyverno.io/category: GPU Management
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    kyverno.io/kyverno-version: 1.11.0
    policies.kyverno.io/description: >-
      Validate that pods requesting GPUs specify the correct resource limits and requests, ensuring they use the proper format (e.g., nvidia.com/gpu: 1).
spec:
  validationFailureAction: Audit
  rules:
    - name: check-gpu-limits-requests
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "Pods requesting GPUs must specify resource limits and requests with the correct format (e.g., nvidia.com/gpu: 1)."
        pattern:
          spec:
            containers:
              - resources:
                  requests:
                    nvidia.com/gpu: ">0"
                  limits:
                    nvidia.com/gpu: ">0"
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: enforce-gpu-node-selector
  annotations:
    policies.kyverno.io/title: Enforce GPU Node Selector
    policies.kyverno.io/category: GPU Management
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    kyverno.io/kyverno-version: 1.11.0
    policies.kyverno.io/description: >-
      Enforce using correct node selectors or node affinity rules for pods requesting GPU resources, ensuring they are scheduled on GPU-capable nodes.
spec:
  validationFailureAction: Audit
  rules:
    - name: check-gpu-node-selector
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "Pods requesting GPU resources must use the correct node selectors or node affinity rules to ensure scheduling on GPU-capable nodes."
        pattern:
          spec:
            nodeSelector:
              kubernetes.io/gpu-node: "true"
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: validate-gpu-tolerations-affinity
  annotations:
    policies.kyverno.io/title: Validate GPU Tolerations and Affinity
    policies.kyverno.io/category: GPU Management
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    kyverno.io/kyverno-version: 1.11.0
    policies.kyverno.io/description: >-
      Validate and inject appropriate tolerations and affinity rules for pods requiring GPUs, ensuring they can be scheduled on nodes with the necessary GPU resources.
spec:
  validationFailureAction: Audit
  rules:
    - name: check-gpu-tolerations-affinity
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "Pods requiring GPUs must have appropriate tolerations and affinity rules to ensure they can be scheduled on nodes with GPU resources."
        pattern:
          spec:
            tolerations:
              - key: "nvidia.com/gpu"
                operator: "Exists"
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                    - matchExpressions:
                        - key: "kubernetes.io/gpu-node"
                          operator: "In"
                          values:
                            - "true"
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: enforce-gpu-resource-quota
  annotations:
    policies.kyverno.io/title: Enforce GPU Resource Quota
    policies.kyverno.io/category: GPU Management
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: ResourceQuota
    kyverno.io/kyverno-version: 1.11.0
    policies.kyverno.io/description: >-
      Enforce ResourceQuota resources that limit the total number of GPUs requested within a namespace used for Ray workloads.
spec:
  validationFailureAction: Audit
  rules:
    - name: check-gpu-resource-quota
      match:
        any:
          - resources:
              kinds:
                - ResourceQuota
      validate:
        message: "ResourceQuota must limit the total number of GPUs requested within a namespace."
        pattern:
          spec:
            hard:
              nvidia.com/gpu: "<=10"
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: enforce-gpu-usage-monitoring
  annotations:
    policies.kyverno.io/title: Enforce GPU Usage Monitoring
    policies.kyverno.io/category: GPU Management
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    kyverno.io/kyverno-version: 1.11.0
    policies.kyverno.io/description: >-
      Ensure the deployment of necessary monitoring components or sidecars that collect and expose GPU usage metrics for Ray workloads.
spec:
  validationFailureAction: Audit
  rules:
    - name: check-gpu-usage-monitoring
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "Pods requiring GPUs must deploy necessary monitoring components or sidecars to collect and expose GPU usage metrics."
        pattern:
          spec:
            containers:
              - name: gpu-monitor
                image: "gpu-monitoring-image"
                resources:
                  requests:
                    cpu: "100m"
                    memory: "200Mi"
