---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: ensure-ray-logging-configurations
  annotations:
    policies.kyverno.io/title: Ensure Ray Logging Configurations
    policies.kyverno.io/category: Logging
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: "Ensure that all Ray-related pods and containers have logging configurations specified, such as log paths and formats."
spec:
  validationFailureAction: Audit
  background: true
  rules:
  - name: validate-logging-configurations
    match:
      any:
      - resources:
          kinds:
          - Pod
          selector:
            matchLabels:
              app: ray
    validate:
      message: "Ray-related pods must specify logging configurations such as log paths and formats."
      pattern:
        spec:
          containers:
          - name: "*"
            volumeMounts:
            - mountPath: "/var/log/ray"
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: enforce-log-rotation-retention
  annotations:
    policies.kyverno.io/title: Enforce Log Rotation and Retention
    policies.kyverno.io/category: Logging
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: "Enforce the presence of appropriate log rotation and retention settings in pod specifications or logging sidecar containers for Ray components."
spec:
  validationFailureAction: Audit
  background: true
  rules:
  - name: validate-log-rotation-retention
    match:
      any:
      - resources:
          kinds:
          - Pod
          selector:
            matchLabels:
              app: ray
    validate:
      message: "Ray-related pods must have log rotation and retention settings configured."
      pattern:
        spec:
          containers:
          - name: "*"
            env:
            - name: LOG_ROTATION
              value: "true"
            - name: LOG_RETENTION_DAYS
              value: "7"
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: validate-log-level-settings
  annotations:
    policies.kyverno.io/title: Validate Log Level Settings
    policies.kyverno.io/category: Logging
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: "Validate and set appropriate log levels for Ray components by checking and modifying environment variables or config maps used for logging configuration."
spec:
  validationFailureAction: Audit
  background: true
  rules:
  - name: enforce-log-level
    match:
      any:
      - resources:
          kinds:
          - Pod
          selector:
            matchLabels:
              app: ray
    validate:
      message: "Ray-related pods must have appropriate log levels set (e.g., INFO, WARN, ERROR)."
      pattern:
        spec:
          containers:
          - name: "*"
            env:
            - name: RAY_LOG_LEVEL
              value: "(INFO|WARN|ERROR)"
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: verify-log-forwarding-configurations
  annotations:
    policies.kyverno.io/title: Verify Log Forwarding Configurations
    policies.kyverno.io/category: Logging
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: "Verify the presence and correct configuration of log forwarding mechanisms, such as fluentd sidecars or appropriate volume mounts for log collection."
spec:
  validationFailureAction: Audit
  background: true
  rules:
  - name: check-log-forwarding
    match:
      any:
      - resources:
          kinds:
          - Pod
          selector:
            matchLabels:
              app: ray
    validate:
      message: "Ray-related pods must have log forwarding mechanisms configured correctly."
      pattern:
        spec:
          containers:
          - name: "*"
            volumeMounts:
            - mountPath: "/var/log/ray"
              name: ray-logs
        volumes:
        - name: ray-logs
          emptyDir: {}
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: enforce-log-format-consistency
  annotations:
    policies.kyverno.io/title: Enforce Log Format Consistency
    policies.kyverno.io/category: Logging
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: "Enforce a standardized log format across Ray components by validating log configuration settings or injecting consistent logging libraries."
spec:
  validationFailureAction: Audit
  background: true
  rules:
  - name: validate-log-format
    match:
      any:
      - resources:
          kinds:
          - Pod
          selector:
            matchLabels:
              app: ray
    validate:
      message: "Ray-related pods must use a standardized log format."
      pattern:
        spec:
          containers:
          - name: "*"
            env:
            - name: LOG_FORMAT
              value: "json"
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: prevent-logging-sensitive-information
  annotations:
    policies.kyverno.io/title: Prevent Logging Sensitive Information
    policies.kyverno.io/category: Logging
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: "Implement policies to scan and prevent the inclusion of sensitive information in log configurations, environment variables, or command arguments that might be logged."
spec:
  validationFailureAction: Audit
  background: true
  rules:
  - name: validate-no-sensitive-info
    match:
      any:
      - resources:
          kinds:
          - Pod
          selector:
            matchLabels:
              app: ray
    validate:
      message: "Ray-related pods must not include sensitive information in log configurations, environment variables, or command arguments."
      pattern:
        spec:
          containers:
          - name: "*"
            env:
            - name: "*"
              value: "!/(password|api_key|token)/"
