---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: prevent-logging-sensitive-env
  annotations:
    policies.kyverno.io/title: Prevent Logging Sensitive Information
    policies.kyverno.io/category: Logging
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: "Implement policies to scan and prevent the inclusion of sensitive information in log configurations, environment variables, or command arguments that might be logged."
spec:
  validationFailureAction: Audit
  background: true
  rules:
  - name: validate-no-sensitive-info
    match:
      any:
      - resources:
          kinds:
          - Pod
          selector:
            matchLabels:
              app: ray
    validate:
      message: "Ray-related pods must not include sensitive information in log configurations, environment variables, or command arguments."
      pattern:
        spec:
          containers:
          - name: "*"
            env:
            - name: "*"
              value: "!/(password|api_key|token)/"
